// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727195341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AUDIT_LOG", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EVENT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock",
                            Status = "Activo",
                            Venue = "Estadio Nacional"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RESERVATION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SEAT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "RowIdentifier", "SeatNumber")
                        .IsUnique();

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            RowIdentifier = "A",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            RowIdentifier = "A",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            RowIdentifier = "A",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            RowIdentifier = "A",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            RowIdentifier = "A",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "A",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "A",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "A",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "A",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "A",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "A",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "A",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "A",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "A",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "A",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001a"),
                            RowIdentifier = "A",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001b"),
                            RowIdentifier = "A",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001c"),
                            RowIdentifier = "A",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001d"),
                            RowIdentifier = "A",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001e"),
                            RowIdentifier = "A",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001f"),
                            RowIdentifier = "A",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "A",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "A",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "A",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "A",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "A",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "A",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "A",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "A",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "A",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "A",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002a"),
                            RowIdentifier = "A",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002b"),
                            RowIdentifier = "A",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002c"),
                            RowIdentifier = "A",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002d"),
                            RowIdentifier = "A",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002e"),
                            RowIdentifier = "A",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002f"),
                            RowIdentifier = "A",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "A",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "A",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "A",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000c"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000d"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000e"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000f"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "B",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "B",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "B",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "B",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "B",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001a"),
                            RowIdentifier = "B",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001b"),
                            RowIdentifier = "B",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001c"),
                            RowIdentifier = "B",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001d"),
                            RowIdentifier = "B",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001e"),
                            RowIdentifier = "B",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000001f"),
                            RowIdentifier = "B",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "B",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "B",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "B",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "B",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "B",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "B",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "B",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "B",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "B",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "B",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002a"),
                            RowIdentifier = "B",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002b"),
                            RowIdentifier = "B",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002c"),
                            RowIdentifier = "B",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002d"),
                            RowIdentifier = "B",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002e"),
                            RowIdentifier = "B",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000002f"),
                            RowIdentifier = "B",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "B",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "B",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "B",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Campo",
                            Price = 5000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Platea",
                            Price = 8000.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.USER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AUDIT_LOG", b =>
                {
                    b.HasOne("Domain.Entities.USER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Domain.Entities.RESERVATION", b =>
                {
                    b.HasOne("Domain.Entities.SEAT", "seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.USER", "user")
                        .WithMany("reserva")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("seat");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Entities.SEAT", b =>
                {
                    b.HasOne("Domain.Entities.SECTOR", "sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sector");
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.HasOne("Domain.Entities.EVENT", "Events")
                        .WithMany("sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Domain.Entities.EVENT", b =>
                {
                    b.Navigation("sectors");
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.USER", b =>
                {
                    b.Navigation("reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
